/**
 * PDF Report Footer Component
 *
 * Displays page numbers, legal disclaimers, and generation info.
 * Renders as a fixed footer at the bottom of each PDF page.
 */

import React from 'react';
import { View, Text } from '@react-pdf/renderer';
import { styles } from './styles';

export interface ReportFooterProps {
  /** Whether to show the full disclaimer section (typically on last page) */
  showFullDisclaimer?: boolean;
}

/**
 * ReportFooter Component
 *
 * Fixed footer that appears at the bottom of each page with:
 * - Legal disclaimer
 * - Generated by attribution
 * - Timestamp
 * - Page numbers (using render prop pattern)
 */
export const ReportFooter: React.FC<ReportFooterProps> = ({
  showFullDisclaimer = false,
}) => {
  const timestamp = new Date().toLocaleString('en-US', {
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
    hour: '2-digit',
    minute: '2-digit',
    second: '2-digit',
    timeZone: 'Asia/Dubai',
  });

  return (
    <>
      {/* Full Disclaimer Section (typically shown on last page) */}
      {showFullDisclaimer && (
        <View style={styles.section}>
          <Text style={styles.sectionHeader}>LEGAL DISCLAIMER</Text>
          <View style={styles.sectionDivider} />

          <Text style={[styles.descriptionText, { fontSize: 9, color: '#666666' }]}>
            <Text style={styles.boldText}>LEGAL DISCLAIMER: </Text>
            This report is generated by TariffAgent AI classification engine and is provided
            for reference purposes only. While we strive for accuracy, this report does not
            constitute official customs advice or authorization. Final HS code classification,
            duty assessment, and clearance decisions rest solely with the UAE Federal Customs
            Authority (FCA). The importer is responsible for ensuring compliance with all UAE
            customs regulations and providing accurate documentation. TariffAgent and its
            operators accept no liability for any losses, penalties, or damages arising from
            reliance on this report.
          </Text>

          <View style={styles.spacer} />

          <Text style={[styles.descriptionText, { fontSize: 9, color: '#00732F' }]}>
            <Text style={styles.boldText}>RECOMMENDATION: </Text>
            Always verify classification with UAE Customs or a licensed customs broker before
            shipment. For complex or high-value shipments, consider obtaining an Advance Ruling
            from UAE Customs.
          </Text>

          <View style={styles.spacerLarge} />

          {/* Attribution */}
          <View style={{ flexDirection: 'row', justifyContent: 'space-between' }}>
            <View>
              <Text style={{ fontSize: 8, color: '#666666', marginBottom: 2 }}>
                <Text style={styles.boldText}>Generated by: </Text>
                TariffAgent AI Classification Engine
              </Text>
              <Text style={{ fontSize: 8, color: '#666666', marginBottom: 2 }}>
                <Text style={styles.boldText}>Website: </Text>
                www.tariffagent.technioz.com
              </Text>
              <Text style={{ fontSize: 8, color: '#666666', marginBottom: 2 }}>
                <Text style={styles.boldText}>Email: </Text>
                gaurav.bhatia@technioz.com
              </Text>
              <Text style={{ fontSize: 8, color: '#666666' }}>
                <Text style={styles.boldText}>Version: </Text>
                v1.0 (2025)
              </Text>
            </View>
          </View>
        </View>
      )}

      {/* Fixed Footer */}
      <View style={styles.footer} fixed>
        {/* Disclaimer Line */}
        <Text style={styles.footerDisclaimer}>
          This report is for reference only. Final classification must be verified with UAE Federal Customs Authority (FCA).
        </Text>

        {/* Bottom Row */}
        <View style={styles.footerBottom}>
          <Text style={styles.footerGenerated}>
            Generated by TariffAgent AI Classification Engine
          </Text>
          <Text
            style={styles.pageNumber}
            render={({ pageNumber, totalPages }) => `Page ${pageNumber} of ${totalPages}`}
            fixed
          />
          <Text style={styles.footerTimestamp}>
            Generated: {timestamp}
          </Text>
        </View>
      </View>
    </>
  );
};

export default ReportFooter;
