'use client';

import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from '@/components/ui/accordion';
import { Bot } from 'lucide-react';

interface AIReasoningProps {
  reasoning: string;
  defaultOpen?: boolean;
}

export function AIReasoning({
  reasoning,
  defaultOpen = false,
}: AIReasoningProps) {
  if (!reasoning) {
    return null;
  }

  return (
    <Accordion
      type="single"
      collapsible
      defaultValue={defaultOpen ? 'reasoning' : undefined}
    >
      <AccordionItem value="reasoning" className="border rounded-lg">
        <AccordionTrigger className="px-4 py-3 hover:bg-gray-50">
          <div className="flex items-center gap-2 text-sm font-semibold">
            <Bot className="h-4 w-4 text-[#00732F]" />
            <span>🤖 AI Classification Reasoning</span>
          </div>
        </AccordionTrigger>
        <AccordionContent className="px-4 pb-4">
          <div className="bg-gray-50 rounded-lg p-4 border border-gray-200">
            {/* Reasoning Content */}
            <div className="prose prose-sm max-w-none text-gray-700">
              {/* Parse and render reasoning with better formatting */}
              {reasoning.split('\n').map((paragraph, index) => {
                // Skip empty lines
                if (!paragraph.trim()) {
                  return null;
                }

                // Check for bullet points
                if (paragraph.trim().startsWith('-') || paragraph.trim().startsWith('•')) {
                  return (
                    <p key={index} className="ml-4 my-1 text-sm">
                      {paragraph}
                    </p>
                  );
                }

                // Check for numbered lists
                if (/^\d+\./.test(paragraph.trim())) {
                  return (
                    <p key={index} className="ml-4 my-1 text-sm font-medium">
                      {paragraph}
                    </p>
                  );
                }

                // Check for headers (lines ending with :)
                if (paragraph.trim().endsWith(':')) {
                  return (
                    <p key={index} className="mt-3 mb-1 text-sm font-semibold text-gray-800">
                      {paragraph}
                    </p>
                  );
                }

                // Regular paragraph
                return (
                  <p key={index} className="my-2 text-sm leading-relaxed">
                    {paragraph}
                  </p>
                );
              })}
            </div>

            {/* Disclaimer */}
            <div className="mt-4 pt-3 border-t border-gray-200">
              <p className="text-xs text-gray-500 italic">
                This reasoning is generated by AI for transparency purposes.
                The actual classification may consider additional factors from
                the UAE customs knowledge base.
              </p>
            </div>
          </div>
        </AccordionContent>
      </AccordionItem>
    </Accordion>
  );
}

export default AIReasoning;
